@startuml
前端 -> 代理商后台: 添加终端用户
代理商后台 -> mysql数据库: 终端用户数据存入数据库
代理商后台 -> 相关产品后台: 终端用户信息和相关产品信息
代理商后台 -> 前端: 成功/失败标识
前端 -> 代理商后台:  添加成功为终端用户添加产品
代理商后台 -> mysql数据库: 终端用户产品数据存入数据库
代理商后台 -> 相关产品后台: 终端用户信息和相关产品信息
@enduml