@startuml
前端 --> 后端: 用户注册信息填写，并获取验证码
后端 --> 第三方短信接口: 发送短信验证码
后端 <-- 第三方短信接口: 返回验证码
后端 --> 数据库: 存储验证码
前端 --> 后端:填写验证码,并注册
后端 --> 数据库:存储用户信息和权限信息
后端 --> 后台刷新项目: 数据存入代理商was_terminal_user,was_terminal_product
后台刷新项目 -->代理商:获取终端用户数据
代理商 --> 相关产品后台: 终端用户信息和相关产品信息
后端 --> 前端:返回成功失败标志
@enduml